config/routes.rb
Webcdist::Application.routes.draw do
  resources :parameters

  resources :cdist_types

  resources :cdist_objects

  resources :cdist_configurations

  resources :tags

  resources :hosts

end

app/models/cdist_configuration.rb
class CdistConfiguration < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/cdist_configurations_controller.rb
class CdistConfigurationsController < ApplicationController
  # GET /cdist_configurations
  # GET /cdist_configurations.json
  def index
    @cdist_configurations = CdistConfiguration.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cdist_configurations }
    end
  end

  # GET /cdist_configurations/1
  # GET /cdist_configurations/1.json
  def show
    @cdist_configuration = CdistConfiguration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cdist_configuration }
    end
  end

  # GET /cdist_configurations/new
  # GET /cdist_configurations/new.json
  def new
    @cdist_configuration = CdistConfiguration.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cdist_configuration }
    end
  end

  # GET /cdist_configurations/1/edit
  def edit
    @cdist_configuration = CdistConfiguration.find(params[:id])
  end

  # POST /cdist_configurations
  # POST /cdist_configurations.json
  def create
    @cdist_configuration = CdistConfiguration.new(params[:cdist_configuration])

    respond_to do |format|
      if @cdist_configuration.save
        format.html { redirect_to @cdist_configuration, notice: 'CdistConfiguration was successfully created.' }
        format.json { render json: @cdist_configuration, status: :created, location: @cdist_configuration }
      else
        format.html { render action: "new" }
        format.json { render json: @cdist_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cdist_configurations/1
  # PUT /cdist_configurations/1.json
  def update
    @cdist_configuration = CdistConfiguration.find(params[:id])

    respond_to do |format|
      if @cdist_configuration.update_attributes(params[:cdist_configuration])
        format.html { redirect_to @cdist_configuration, notice: 'CdistConfiguration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cdist_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cdist_configurations/1
  # DELETE /cdist_configurations/1.json
  def destroy
    @cdist_configuration = CdistConfiguration.find(params[:id])
    @cdist_configuration.destroy

    respond_to do |format|
      format.html { redirect_to cdist_configurations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cdist_configurations_helper.rb
module CdistConfigurationsHelper
end

app/views/cdist_configurations/_form.html.erb
<%= form_for(@cdist_configuration) do |f| %>
  <% if @cdist_configuration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cdist_configuration.errors.count, "error") %> prohibited this cdist configuration from being saved:</h2>

      <ul>
      <% @cdist_configuration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cdist_configurations/edit.html.erb
<h1>Editing cdist configuration</h1>

<%= render 'form' %>

<%= link_to 'Show', @cdist_configuration %> |
<%= link_to 'Back', cdist_configurations_path %>

app/views/cdist_configurations/index.html.erb
<h1>Listing cdist configurations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>

<% @cdist_configurations.each do |cdist_configuration| %>
  <tr>
    <td><%= cdist_configuration.name %></td>
    <td><%= cdist_configuration.description %></td>
    <td><%= link_to 'Show', cdist_configuration %></td>
    <td><%= link_to 'Edit', edit_cdist_configuration_path(cdist_configuration) %></td>
    <td><%= link_to 'Destroy', cdist_configuration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New cdist configuration', new_cdist_configuration_path %>

app/views/cdist_configurations/new.html.erb
<h1>New cdist configuration</h1>

<%= render 'form' %>

<%= link_to 'Back', cdist_configurations_path %>

app/views/cdist_configurations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @cdist_configuration.name %>
</p>

<p>
  <b>Description:</b>
  <%= @cdist_configuration.description %>
</p>


<%= link_to 'Edit', edit_cdist_configuration_path(@cdist_configuration) %> |
<%= link_to 'Back', cdist_configurations_path %>