config/routes.rb
Webcdist::Application.routes.draw do
  resources :parameters

  resources :cdist_types

  resources :cdist_objects

  resources :cdist_configurations

  resources :tags

  resources :hosts

end

app/models/cdist_object.rb
class CdistObject < ActiveRecord::Base
  attr_accessible :cdist_type
end

app/controllers/cdist_objects_controller.rb
class CdistObjectsController < ApplicationController
  # GET /cdist_objects
  # GET /cdist_objects.json
  def index
    @cdist_objects = CdistObject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cdist_objects }
    end
  end

  # GET /cdist_objects/1
  # GET /cdist_objects/1.json
  def show
    @cdist_object = CdistObject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cdist_object }
    end
  end

  # GET /cdist_objects/new
  # GET /cdist_objects/new.json
  def new
    @cdist_object = CdistObject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cdist_object }
    end
  end

  # GET /cdist_objects/1/edit
  def edit
    @cdist_object = CdistObject.find(params[:id])
  end

  # POST /cdist_objects
  # POST /cdist_objects.json
  def create
    @cdist_object = CdistObject.new(params[:cdist_object])

    respond_to do |format|
      if @cdist_object.save
        format.html { redirect_to @cdist_object, notice: 'Cdist object was successfully created.' }
        format.json { render json: @cdist_object, status: :created, location: @cdist_object }
      else
        format.html { render action: "new" }
        format.json { render json: @cdist_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cdist_objects/1
  # PUT /cdist_objects/1.json
  def update
    @cdist_object = CdistObject.find(params[:id])

    respond_to do |format|
      if @cdist_object.update_attributes(params[:cdist_object])
        format.html { redirect_to @cdist_object, notice: 'Cdist object was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cdist_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cdist_objects/1
  # DELETE /cdist_objects/1.json
  def destroy
    @cdist_object = CdistObject.find(params[:id])
    @cdist_object.destroy

    respond_to do |format|
      format.html { redirect_to cdist_objects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cdist_objects_helper.rb
module CdistObjectsHelper
end

app/views/cdist_objects/_form.html.erb
<%= form_for(@cdist_object) do |f| %>
  <% if @cdist_object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cdist_object.errors.count, "error") %> prohibited this cdist_object from being saved:</h2>

      <ul>
      <% @cdist_object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cdist_type %><br />
    <%= f.number_field :cdist_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cdist_objects/edit.html.erb
<h1>Editing cdist_object</h1>

<%= render 'form' %>

<%= link_to 'Show', @cdist_object %> |
<%= link_to 'Back', cdist_objects_path %>

app/views/cdist_objects/index.html.erb
<h1>Listing cdist_objects</h1>

<table>
  <tr>
    <th>Cdist type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cdist_objects.each do |cdist_object| %>
  <tr>
    <td><%= cdist_object.cdist_type %></td>
    <td><%= link_to 'Show', cdist_object %></td>
    <td><%= link_to 'Edit', edit_cdist_object_path(cdist_object) %></td>
    <td><%= link_to 'Destroy', cdist_object, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cdist object', new_cdist_object_path %>

app/views/cdist_objects/new.html.erb
<h1>New cdist_object</h1>

<%= render 'form' %>

<%= link_to 'Back', cdist_objects_path %>

app/views/cdist_objects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cdist type:</b>
  <%= @cdist_object.cdist_type %>
</p>


<%= link_to 'Edit', edit_cdist_object_path(@cdist_object) %> |
<%= link_to 'Back', cdist_objects_path %>