config/routes.rb
Webcdist::Application.routes.draw do
  resources :parameters

  resources :cdist_types

  resources :cdist_objects

  resources :cdist_configurations

  resources :tags

  resources :hosts

end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  attr_accessible :name, :type
end

app/controllers/parameters_controller.rb
class ParametersController < ApplicationController
  # GET /parameters
  # GET /parameters.json
  def index
    @parameters = Parameter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parameters }
    end
  end

  # GET /parameters/1
  # GET /parameters/1.json
  def show
    @parameter = Parameter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @parameter }
    end
  end

  # GET /parameters/new
  # GET /parameters/new.json
  def new
    @parameter = Parameter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @parameter }
    end
  end

  # GET /parameters/1/edit
  def edit
    @parameter = Parameter.find(params[:id])
  end

  # POST /parameters
  # POST /parameters.json
  def create
    @parameter = Parameter.new(params[:parameter])

    respond_to do |format|
      if @parameter.save
        format.html { redirect_to @parameter, notice: 'Parameter was successfully created.' }
        format.json { render json: @parameter, status: :created, location: @parameter }
      else
        format.html { render action: "new" }
        format.json { render json: @parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parameters/1
  # PUT /parameters/1.json
  def update
    @parameter = Parameter.find(params[:id])

    respond_to do |format|
      if @parameter.update_attributes(params[:parameter])
        format.html { redirect_to @parameter, notice: 'Parameter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parameters/1
  # DELETE /parameters/1.json
  def destroy
    @parameter = Parameter.find(params[:id])
    @parameter.destroy

    respond_to do |format|
      format.html { redirect_to parameters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/parameters_helper.rb
module ParametersHelper
end

app/views/parameters/_form.html.erb
<%= form_for(@parameter) do |f| %>
  <% if @parameter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parameter.errors.count, "error") %> prohibited this parameter from being saved:</h2>

      <ul>
      <% @parameter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_area :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parameters/edit.html.erb
<h1>Editing parameter</h1>

<%= render 'form' %>

<%= link_to 'Show', @parameter %> |
<%= link_to 'Back', parameters_path %>

app/views/parameters/index.html.erb
<h1>Listing parameters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parameters.each do |parameter| %>
  <tr>
    <td><%= parameter.name %></td>
    <td><%= parameter.type %></td>
    <td><%= link_to 'Show', parameter %></td>
    <td><%= link_to 'Edit', edit_parameter_path(parameter) %></td>
    <td><%= link_to 'Destroy', parameter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Parameter', new_parameter_path %>

app/views/parameters/new.html.erb
<h1>New parameter</h1>

<%= render 'form' %>

<%= link_to 'Back', parameters_path %>

app/views/parameters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @parameter.name %>
</p>

<p>
  <b>Type:</b>
  <%= @parameter.type %>
</p>


<%= link_to 'Edit', edit_parameter_path(@parameter) %> |
<%= link_to 'Back', parameters_path %>